import type {
  ElementCategory,
  ElementTypeId,
  McbProperties,
  RcdProperties,
  RcboProperties,
  IsolatorProperties,
  VoltageRelayProperties,
  GenericProperties,
  ElementProperties,
} from '../types/panel'

export interface ElementDef {
  id: ElementTypeId
  label: string
  shortLabel: string
  category: ElementCategory
  defaultSlotWidth: number
  defaultLabel: string
  color: string
  textColor: string
  description: string
  poles: number
  defaultProperties: ElementProperties
}

const MCB_DEFAULT: McbProperties = { kind: 'mcb', rating: 16, curve: 'C', breakingCapacity: 6 }
const VR_DEFAULT: VoltageRelayProperties = { kind: 'voltage_relay', minVoltage: 195, maxVoltage: 253, delaySeconds: 5 }
const RCD_DEFAULT: RcdProperties = { kind: 'rcd', rating: 63, sensitivity: 30, type: 'A' }
const RCBO_DEFAULT: RcboProperties = { kind: 'rcbo', rating: 16, curve: 'C', sensitivity: 30, type: 'A', breakingCapacity: 6 }
const ISO_DEFAULT: IsolatorProperties = { kind: 'isolator', rating: 63 }
const GENERIC: GenericProperties = { kind: 'generic' }

export const ELEMENT_DEFS: ElementDef[] = [
  {
    id: 'mcb_1p',
    label: '1P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 1,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Single-pole miniature circuit breaker',
    poles: 1,
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'mcb_2p',
    label: '2P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Double-pole miniature circuit breaker',
    poles: 2,
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'mcb_3p',
    label: '3P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 3,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Triple-pole miniature circuit breaker',
    poles: 3,
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'mcb_4p',
    label: '4P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 4,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Four-pole miniature circuit breaker',
    poles: 4,
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'rcd_2p',
    label: '2P RCD',
    shortLabel: 'RCD',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'RCD',
    color: '#7c3aed',
    textColor: '#ffffff',
    description: 'Two-pole residual current device',
    poles: 2,
    defaultProperties: { ...RCD_DEFAULT },
  },
  {
    id: 'rcd_4p',
    label: '4P RCD',
    shortLabel: 'RCD',
    category: 'protection',
    defaultSlotWidth: 4,
    defaultLabel: 'RCD',
    color: '#7c3aed',
    textColor: '#ffffff',
    description: 'Four-pole residual current device',
    poles: 4,
    defaultProperties: { ...RCD_DEFAULT },
  },
  {
    id: 'rcbo_1p',
    label: '1P RCBO',
    shortLabel: 'RCBO',
    category: 'protection',
    defaultSlotWidth: 1,
    defaultLabel: 'RCBO',
    color: '#be185d',
    textColor: '#ffffff',
    description: 'Single-pole residual current breaker with overload',
    poles: 1,
    defaultProperties: { ...RCBO_DEFAULT },
  },
  {
    id: 'rcbo_2p',
    label: '2P RCBO',
    shortLabel: 'RCBO',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'RCBO',
    color: '#be185d',
    textColor: '#ffffff',
    description: 'Double-pole residual current breaker with overload',
    poles: 2,
    defaultProperties: { ...RCBO_DEFAULT },
  },
  {
    id: 'rcbo_4p',
    label: '4P RCBO',
    shortLabel: 'RCBO',
    category: 'protection',
    defaultSlotWidth: 4,
    defaultLabel: 'RCBO',
    color: '#be185d',
    textColor: '#ffffff',
    description: 'Four-pole residual current breaker with overload',
    poles: 4,
    defaultProperties: { ...RCBO_DEFAULT },
  },
  {
    id: 'isolator_1p',
    label: '1P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 1,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Single-pole isolating switch',
    poles: 1,
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'isolator_2p',
    label: '2P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Double-pole isolating switch',
    poles: 2,
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'isolator_3p',
    label: '3P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 3,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Triple-pole isolating switch',
    poles: 3,
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'isolator_4p',
    label: '4P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 4,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Four-pole isolating switch',
    poles: 4,
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'main_switch_2p',
    label: '2P Main Switch',
    shortLabel: 'MAIN',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Main',
    color: '#991b1b',
    textColor: '#ffffff',
    description: 'Two-pole main isolator / supply disconnector',
    poles: 2,
    defaultProperties: { ...ISO_DEFAULT, rating: 100 },
  },
  {
    id: 'main_switch_4p',
    label: '4P Main Switch',
    shortLabel: 'MAIN',
    category: 'switching',
    defaultSlotWidth: 4,
    defaultLabel: 'Main',
    color: '#991b1b',
    textColor: '#ffffff',
    description: 'Four-pole main isolator / supply disconnector',
    poles: 4,
    defaultProperties: { ...ISO_DEFAULT, rating: 100 },
  },
  {
    id: 'cross_2p',
    label: '2P Cross Connector',
    shortLabel: 'CROSS',
    category: 'distribution',
    defaultSlotWidth: 4,
    defaultLabel: 'Cross',
    color: '#c2410c',
    textColor: '#ffffff',
    description: '2-pole distribution cross connector — fans L+N to multiple circuits',
    poles: 2,
    defaultProperties: GENERIC,
  },
  {
    id: 'contactor_3p',
    label: '3P Contactor',
    shortLabel: 'CTR',
    category: 'switching',
    defaultSlotWidth: 3,
    defaultLabel: 'Contactor',
    color: '#b45309',
    textColor: '#ffffff',
    description: 'Three-pole contactor',
    poles: 3,
    defaultProperties: { kind: 'generic', rating: 25 } as GenericProperties,
  },
  {
    id: 'timer',
    label: 'Timer Switch',
    shortLabel: 'TMR',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Timer',
    color: '#92400e',
    textColor: '#ffffff',
    description: 'DIN rail time switch',
    poles: 1,
    defaultProperties: GENERIC,
  },
  {
    id: 'surge_protector',
    label: 'Surge Protector',
    shortLabel: 'SPD',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'SPD',
    color: '#dc2626',
    textColor: '#ffffff',
    description: 'Surge protection device',
    poles: 2,
    defaultProperties: GENERIC,
  },
  {
    id: 'neutral_bar',
    label: 'Neutral Bar',
    shortLabel: 'N',
    category: 'distribution',
    defaultSlotWidth: 2,
    defaultLabel: 'N Bar',
    color: '#0284c7',
    textColor: '#ffffff',
    description: 'Neutral distribution bar',
    poles: 0,
    defaultProperties: GENERIC,
  },
  {
    id: 'earth_bar',
    label: 'Earth Bar',
    shortLabel: 'PE',
    category: 'distribution',
    defaultSlotWidth: 2,
    defaultLabel: 'PE Bar',
    color: '#15803d',
    textColor: '#ffffff',
    description: 'Earth/PE distribution bar',
    poles: 0,
    defaultProperties: GENERIC,
  },
  {
    id: 'busbar_connector',
    label: 'Busbar',
    shortLabel: 'BUS',
    category: 'distribution',
    defaultSlotWidth: 4,
    defaultLabel: 'Busbar',
    color: '#6b7280',
    textColor: '#ffffff',
    description: 'Busbar connector',
    poles: 0,
    defaultProperties: GENERIC,
  },
  {
    id: 'voltage_relay',
    label: 'Voltage Relay',
    shortLabel: 'VR',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'Volt Relay',
    color: '#4338ca',
    textColor: '#ffffff',
    description: 'Voltage monitoring relay — trips on over/under-voltage',
    poles: 2,
    defaultProperties: { ...VR_DEFAULT },
  },
  {
    id: 'blank',
    label: 'Blank Filler',
    shortLabel: '—',
    category: 'accessory',
    defaultSlotWidth: 1,
    defaultLabel: '',
    color: '#e5e7eb',
    textColor: '#374151',
    description: 'Blank filler module',
    poles: 0,
    defaultProperties: GENERIC,
  },
]

export const ELEMENT_DEFS_MAP = new Map<ElementTypeId, ElementDef>(
  ELEMENT_DEFS.map((d) => [d.id, d])
)
