import type {
  ElementCategory,
  ElementTypeId,
  McbProperties,
  RcdProperties,
  RcboProperties,
  IsolatorProperties,
  VoltageRelayProperties,
  ContactorProperties,
  SurgeProtectorProperties,
  TimerProperties,
  MeterProperties,
  SignalLampProperties,
  SocketProperties,
  ButtonProperties,
  MotorStarterProperties,
  BuzzerProperties,
  DimmerProperties,
  GenericProperties,
  ElementProperties,
} from '../types/panel'

/**
 * Symbol identifier — a stable key used by the ElementShape symbol registry.
 * Adding a new element type only requires registering a new symbol here,
 * keeping ElementShape closed for modification (OCP).
 */
export type SymbolId =
  | 'mcb'
  | 'rcd'
  | 'rcbo'
  | 'isolator'
  | 'main_switch'
  | 'cross'
  | 'contactor'
  | 'timer'
  | 'surge_protector'
  | 'neutral_bar'
  | 'earth_bar'
  | 'busbar'
  | 'voltage_relay'
  | 'kwh_meter'
  | 'signal_lamp'
  | 'modular_socket'
  | 'push_button'
  | 'motor_starter'
  | 'buzzer'
  | 'dimmer'
  | 'blank'

export interface ElementDef {
  id: ElementTypeId
  label: string
  shortLabel: string
  category: ElementCategory
  defaultSlotWidth: number
  defaultLabel: string
  color: string
  textColor: string
  description: string
  poles: number
  symbolId: SymbolId
  defaultProperties: ElementProperties
}

const MCB_DEFAULT: McbProperties = { kind: 'mcb', rating: 16, curve: 'C', breakingCapacity: 6 }
const VR_DEFAULT: VoltageRelayProperties = { kind: 'voltage_relay', minVoltage: 195, maxVoltage: 253, delaySeconds: 5 }
const RCD_DEFAULT: RcdProperties = { kind: 'rcd', rating: 63, sensitivity: 30, type: 'A' }
const RCBO_DEFAULT: RcboProperties = { kind: 'rcbo', rating: 16, curve: 'C', sensitivity: 30, type: 'A', breakingCapacity: 6 }
const ISO_DEFAULT: IsolatorProperties = { kind: 'isolator', rating: 63 }
const CONTACTOR_DEFAULT: Omit<ContactorProperties, 'poles'> = {
  kind: 'contactor', rating: 25, coilVoltage: 230,
}
const SPD_DEFAULT: SurgeProtectorProperties = {
  kind: 'surge_protector', type: 'T2', nominalCurrent: 20, protectionLevel: 1.5, maxOperatingVoltage: 275,
}
const TIMER_DEFAULT: TimerProperties = { kind: 'timer', mode: 'weekly', rating: 16 }
const METER_DEFAULT: MeterProperties = { kind: 'meter', rating: 63, threePhase: false, midClass: 'B' }
const LAMP_DEFAULT: SignalLampProperties = { kind: 'signal_lamp', color: 'green', voltage: 230 }
const SOCKET_DEFAULT: SocketProperties = { kind: 'socket', rating: 16, standard: 'schuko' }
const BUTTON_DEFAULT: ButtonProperties = { kind: 'button', variant: 'push', color: 'green' }
const MOTOR_DEFAULT: MotorStarterProperties = { kind: 'motor_starter', rating: 10, powerKw: 4, overloadClass: '10A' }
const BUZZER_DEFAULT: BuzzerProperties = { kind: 'buzzer', voltage: 230 }
const DIMMER_DEFAULT: DimmerProperties = { kind: 'dimmer', rating: 6, maxWatts: 400, loadType: 'led' }
const GENERIC: GenericProperties = { kind: 'generic' }

export const ELEMENT_DEFS: ElementDef[] = [
  {
    id: 'mcb_1p',
    label: '1P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 1,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Single-pole miniature circuit breaker',
    poles: 1,
    symbolId: 'mcb',
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'mcb_2p',
    label: '2P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Double-pole miniature circuit breaker',
    poles: 2,
    symbolId: 'mcb',
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'mcb_3p',
    label: '3P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 3,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Triple-pole miniature circuit breaker',
    poles: 3,
    symbolId: 'mcb',
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'mcb_4p',
    label: '4P MCB',
    shortLabel: 'MCB',
    category: 'protection',
    defaultSlotWidth: 4,
    defaultLabel: 'MCB',
    color: '#1d4ed8',
    textColor: '#ffffff',
    description: 'Four-pole miniature circuit breaker',
    poles: 4,
    symbolId: 'mcb',
    defaultProperties: { ...MCB_DEFAULT },
  },
  {
    id: 'rcd_2p',
    label: '2P RCD',
    shortLabel: 'RCD',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'RCD',
    color: '#7c3aed',
    textColor: '#ffffff',
    description: 'Two-pole residual current device',
    poles: 2,
    symbolId: 'rcd',
    defaultProperties: { ...RCD_DEFAULT },
  },
  {
    id: 'rcd_4p',
    label: '4P RCD',
    shortLabel: 'RCD',
    category: 'protection',
    defaultSlotWidth: 4,
    defaultLabel: 'RCD',
    color: '#7c3aed',
    textColor: '#ffffff',
    description: 'Four-pole residual current device',
    poles: 4,
    symbolId: 'rcd',
    defaultProperties: { ...RCD_DEFAULT },
  },
  {
    id: 'rcbo_1p',
    label: '1P RCBO',
    shortLabel: 'RCBO',
    category: 'protection',
    defaultSlotWidth: 1,
    defaultLabel: 'RCBO',
    color: '#be185d',
    textColor: '#ffffff',
    description: 'Single-pole residual current breaker with overload',
    poles: 1,
    symbolId: 'rcbo',
    defaultProperties: { ...RCBO_DEFAULT },
  },
  {
    id: 'rcbo_2p',
    label: '2P RCBO',
    shortLabel: 'RCBO',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'RCBO',
    color: '#be185d',
    textColor: '#ffffff',
    description: 'Double-pole residual current breaker with overload',
    poles: 2,
    symbolId: 'rcbo',
    defaultProperties: { ...RCBO_DEFAULT },
  },
  {
    id: 'rcbo_4p',
    label: '4P RCBO',
    shortLabel: 'RCBO',
    category: 'protection',
    defaultSlotWidth: 4,
    defaultLabel: 'RCBO',
    color: '#be185d',
    textColor: '#ffffff',
    description: 'Four-pole residual current breaker with overload',
    poles: 4,
    symbolId: 'rcbo',
    defaultProperties: { ...RCBO_DEFAULT },
  },
  {
    id: 'isolator_1p',
    label: '1P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 1,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Single-pole isolating switch',
    poles: 1,
    symbolId: 'isolator',
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'isolator_2p',
    label: '2P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Double-pole isolating switch',
    poles: 2,
    symbolId: 'isolator',
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'isolator_3p',
    label: '3P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 3,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Triple-pole isolating switch',
    poles: 3,
    symbolId: 'isolator',
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'isolator_4p',
    label: '4P Isolator',
    shortLabel: 'ISO',
    category: 'switching',
    defaultSlotWidth: 4,
    defaultLabel: 'Isolator',
    color: '#0f766e',
    textColor: '#ffffff',
    description: 'Four-pole isolating switch',
    poles: 4,
    symbolId: 'isolator',
    defaultProperties: { ...ISO_DEFAULT },
  },
  {
    id: 'main_switch_2p',
    label: '2P Main Switch',
    shortLabel: 'MAIN',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Main',
    color: '#991b1b',
    textColor: '#ffffff',
    description: 'Two-pole main isolator / supply disconnector',
    poles: 2,
    symbolId: 'main_switch',
    defaultProperties: { ...ISO_DEFAULT, rating: 100 },
  },
  {
    id: 'main_switch_4p',
    label: '4P Main Switch',
    shortLabel: 'MAIN',
    category: 'switching',
    defaultSlotWidth: 4,
    defaultLabel: 'Main',
    color: '#991b1b',
    textColor: '#ffffff',
    description: 'Four-pole main isolator / supply disconnector',
    poles: 4,
    symbolId: 'main_switch',
    defaultProperties: { ...ISO_DEFAULT, rating: 100 },
  },
  {
    id: 'cross_2p',
    label: '2P Cross Connector',
    shortLabel: 'CROSS',
    category: 'distribution',
    defaultSlotWidth: 4,
    defaultLabel: 'Cross',
    color: '#c2410c',
    textColor: '#ffffff',
    description: '2-pole distribution cross connector — fans L+N to multiple circuits',
    poles: 2,
    symbolId: 'cross',
    defaultProperties: GENERIC,
  },
  {
    id: 'contactor_2p',
    label: '2P Contactor',
    shortLabel: 'CTR',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Contactor',
    color: '#b45309',
    textColor: '#ffffff',
    description: 'Two-pole modular contactor',
    poles: 2,
    symbolId: 'contactor',
    defaultProperties: { ...CONTACTOR_DEFAULT, poles: 2 },
  },
  {
    id: 'contactor_3p',
    label: '3P Contactor',
    shortLabel: 'CTR',
    category: 'switching',
    defaultSlotWidth: 3,
    defaultLabel: 'Contactor',
    color: '#b45309',
    textColor: '#ffffff',
    description: 'Three-pole contactor',
    poles: 3,
    symbolId: 'contactor',
    defaultProperties: { ...CONTACTOR_DEFAULT, poles: 3 },
  },
  {
    id: 'contactor_4p',
    label: '4P Contactor',
    shortLabel: 'CTR',
    category: 'switching',
    defaultSlotWidth: 4,
    defaultLabel: 'Contactor',
    color: '#b45309',
    textColor: '#ffffff',
    description: 'Four-pole contactor',
    poles: 4,
    symbolId: 'contactor',
    defaultProperties: { ...CONTACTOR_DEFAULT, poles: 4 },
  },
  {
    id: 'timer',
    label: 'Timer Switch',
    shortLabel: 'TMR',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Timer',
    color: '#92400e',
    textColor: '#ffffff',
    description: 'DIN rail time switch (astronomical / weekly / countdown / staircase)',
    poles: 1,
    symbolId: 'timer',
    defaultProperties: { ...TIMER_DEFAULT },
  },
  {
    id: 'surge_protector',
    label: 'Surge Protector',
    shortLabel: 'SPD',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'SPD',
    color: '#dc2626',
    textColor: '#ffffff',
    description: 'Surge protection device (Type 1/2/3)',
    poles: 2,
    symbolId: 'surge_protector',
    defaultProperties: { ...SPD_DEFAULT },
  },
  {
    id: 'kwh_meter',
    label: 'kWh Meter',
    shortLabel: 'kWh',
    category: 'accessory',
    defaultSlotWidth: 4,
    defaultLabel: 'Meter',
    color: '#0369a1',
    textColor: '#ffffff',
    description: 'Modular energy meter (MID)',
    poles: 1,
    symbolId: 'kwh_meter',
    defaultProperties: { ...METER_DEFAULT },
  },
  {
    id: 'signal_lamp',
    label: 'Signal Lamp',
    shortLabel: 'LAMP',
    category: 'accessory',
    defaultSlotWidth: 1,
    defaultLabel: 'Lamp',
    color: '#eab308',
    textColor: '#000000',
    description: 'Phase/status indicator lamp',
    poles: 1,
    symbolId: 'signal_lamp',
    defaultProperties: { ...LAMP_DEFAULT },
  },
  {
    id: 'modular_socket',
    label: 'DIN Socket',
    shortLabel: 'SOC',
    category: 'accessory',
    defaultSlotWidth: 3,
    defaultLabel: 'Socket',
    color: '#059669',
    textColor: '#ffffff',
    description: 'Modular DIN rail socket outlet',
    poles: 2,
    symbolId: 'modular_socket',
    defaultProperties: { ...SOCKET_DEFAULT },
  },
  {
    id: 'push_button',
    label: 'Push Button',
    shortLabel: 'BTN',
    category: 'switching',
    defaultSlotWidth: 1,
    defaultLabel: 'Button',
    color: '#0d9488',
    textColor: '#ffffff',
    description: 'Modular push button (control)',
    poles: 1,
    symbolId: 'push_button',
    defaultProperties: { ...BUTTON_DEFAULT },
  },
  {
    id: 'motor_starter',
    label: 'Motor Starter',
    shortLabel: 'MS',
    category: 'protection',
    defaultSlotWidth: 3,
    defaultLabel: 'Motor',
    color: '#65a30d',
    textColor: '#ffffff',
    description: 'Motor circuit breaker / thermal overload',
    poles: 3,
    symbolId: 'motor_starter',
    defaultProperties: { ...MOTOR_DEFAULT },
  },
  {
    id: 'buzzer',
    label: 'Buzzer',
    shortLabel: 'BUZ',
    category: 'accessory',
    defaultSlotWidth: 1,
    defaultLabel: 'Buzzer',
    color: '#7c2d12',
    textColor: '#ffffff',
    description: 'Modular DIN buzzer / chime',
    poles: 1,
    symbolId: 'buzzer',
    defaultProperties: { ...BUZZER_DEFAULT },
  },
  {
    id: 'dimmer',
    label: 'Dimmer',
    shortLabel: 'DIM',
    category: 'switching',
    defaultSlotWidth: 2,
    defaultLabel: 'Dimmer',
    color: '#9333ea',
    textColor: '#ffffff',
    description: 'Modular DIN dimmer — universal LED / halogen / incandescent',
    poles: 1,
    symbolId: 'dimmer',
    defaultProperties: { ...DIMMER_DEFAULT },
  },
  {
    id: 'neutral_bar',
    label: 'Neutral Bar',
    shortLabel: 'N',
    category: 'distribution',
    defaultSlotWidth: 2,
    defaultLabel: 'N Bar',
    color: '#0284c7',
    textColor: '#ffffff',
    description: 'Neutral distribution bar',
    poles: 0,
    symbolId: 'neutral_bar',
    defaultProperties: GENERIC,
  },
  {
    id: 'earth_bar',
    label: 'Earth Bar',
    shortLabel: 'PE',
    category: 'distribution',
    defaultSlotWidth: 2,
    defaultLabel: 'PE Bar',
    color: '#15803d',
    textColor: '#ffffff',
    description: 'Earth/PE distribution bar',
    poles: 0,
    symbolId: 'earth_bar',
    defaultProperties: GENERIC,
  },
  {
    id: 'busbar_connector',
    label: 'Busbar',
    shortLabel: 'BUS',
    category: 'distribution',
    defaultSlotWidth: 4,
    defaultLabel: 'Busbar',
    color: '#6b7280',
    textColor: '#ffffff',
    description: 'Busbar connector',
    poles: 0,
    symbolId: 'busbar',
    defaultProperties: GENERIC,
  },
  {
    id: 'voltage_relay',
    label: 'Voltage Relay',
    shortLabel: 'VR',
    category: 'protection',
    defaultSlotWidth: 2,
    defaultLabel: 'Volt Relay',
    color: '#4338ca',
    textColor: '#ffffff',
    description: 'Voltage monitoring relay — trips on over/under-voltage',
    poles: 2,
    symbolId: 'voltage_relay',
    defaultProperties: { ...VR_DEFAULT },
  },
  {
    id: 'blank',
    label: 'Blank Filler',
    shortLabel: '—',
    category: 'accessory',
    defaultSlotWidth: 1,
    defaultLabel: '',
    color: '#e5e7eb',
    textColor: '#374151',
    description: 'Blank filler module',
    poles: 0,
    symbolId: 'blank',
    defaultProperties: GENERIC,
  },
]

export const ELEMENT_DEFS_MAP = new Map<ElementTypeId, ElementDef>(
  ELEMENT_DEFS.map((d) => [d.id, d])
)
