import type { SchemeNodeType, SchemeDef } from '../types/scheme'

export const SCHEME_DEFS: Record<SchemeNodeType, SchemeDef> = {
  switch_spst: {
    label: 'Switch (SPST)',
    description: 'Single-pole single-throw switch',
    width: 80,
    height: 48,
    color: '#1d4ed8',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'in', x: 0, y: 24 },
      { index: 1, label: 'out', x: 80, y: 24 },
    ],
  },
  lamp_230: {
    label: 'Lamp 230V',
    description: 'Incandescent lamp 230V',
    width: 64,
    height: 64,
    color: '#d97706',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L', x: 32, y: 0 },
      { index: 1, label: 'N', x: 32, y: 64 },
    ],
  },
  led_220: {
    label: 'LED 220V',
    description: 'LED lamp 220V',
    width: 64,
    height: 64,
    color: '#059669',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: '+', x: 32, y: 0 },
      { index: 1, label: '-', x: 32, y: 64 },
    ],
  },
  transformer_sd: {
    label: 'Transformer',
    description: 'Step-down transformer',
    width: 128,
    height: 80,
    color: '#7c3aed',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L1', x: 0, y: 24 },
      { index: 1, label: 'N1', x: 0, y: 56 },
      { index: 2, label: 'L2', x: 128, y: 24 },
      { index: 3, label: 'N2', x: 128, y: 56 },
    ],
  },
  power_ac: {
    label: 'AC Power',
    description: 'AC mains power inlet',
    width: 80,
    height: 64,
    color: '#dc2626',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L', x: 20, y: 64 },
      { index: 1, label: 'N', x: 40, y: 64 },
      { index: 2, label: 'PE', x: 60, y: 64 },
    ],
  },
  junction: {
    label: 'Junction',
    description: 'Wire junction point',
    width: 16,
    height: 16,
    color: '#374151',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: '', x: 8, y: 0 },
      { index: 1, label: '', x: 16, y: 8 },
      { index: 2, label: '', x: 8, y: 16 },
      { index: 3, label: '', x: 0, y: 8 },
    ],
  },
  socket_outlet: {
    label: 'Socket 2P+E',
    description: 'Electrical socket (2P+E)',
    width: 72,
    height: 64,
    color: '#0891b2',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L', x: 20, y: 64 },
      { index: 1, label: 'N', x: 36, y: 64 },
      { index: 2, label: 'PE', x: 52, y: 64 },
    ],
  },
  push_button: {
    label: 'Push Button',
    description: 'Momentary push button (NO)',
    width: 64,
    height: 48,
    color: '#0f766e',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'in', x: 0, y: 24 },
      { index: 1, label: 'out', x: 64, y: 24 },
    ],
  },
  switch_2way: {
    label: 'Switch 2-way',
    description: 'Two-way / staircase switch',
    width: 88,
    height: 56,
    color: '#7c3aed',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'C', x: 0, y: 28 },
      { index: 1, label: 'A', x: 88, y: 16 },
      { index: 2, label: 'B', x: 88, y: 40 },
    ],
  },
  motor: {
    label: 'Motor',
    description: 'Motor / pump load',
    width: 72,
    height: 72,
    color: '#b45309',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L', x: 20, y: 0 },
      { index: 1, label: 'N', x: 52, y: 0 },
      { index: 2, label: 'PE', x: 36, y: 72 },
    ],
  },
  switch_intermediate: {
    label: 'Intermediate switch',
    description: '4-terminal cross switch — sits between two 2-way switches for 3+ control points',
    width: 96,
    height: 64,
    color: '#7c3aed',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'A1', x: 0,  y: 20 },
      { index: 1, label: 'A2', x: 0,  y: 44 },
      { index: 2, label: 'B1', x: 96, y: 20 },
      { index: 3, label: 'B2', x: 96, y: 44 },
    ],
  },
  contactor: {
    label: 'Contactor',
    description: '3-phase contactor with coil control (A1/A2)',
    width: 96,
    height: 88,
    color: '#0d9488',
    textColor: '#ffffff',
    ports: [
      // Main pole terminals — top = line side, bottom = load side
      { index: 0, label: 'L1', x: 20, y: 0 },
      { index: 1, label: 'L2', x: 48, y: 0 },
      { index: 2, label: 'L3', x: 76, y: 0 },
      { index: 3, label: 'T1', x: 20, y: 88 },
      { index: 4, label: 'T2', x: 48, y: 88 },
      { index: 5, label: 'T3', x: 76, y: 88 },
      // Coil terminals (control voltage)
      { index: 6, label: 'A1', x: 0,  y: 30 },
      { index: 7, label: 'A2', x: 0,  y: 58 },
    ],
  },
  overload: {
    label: 'Thermal overload',
    description: 'Thermal overload relay with 95/96 NC contact for the coil circuit',
    width: 96,
    height: 72,
    color: '#dc2626',
    textColor: '#ffffff',
    ports: [
      // Main power pass-through (from contactor T1/T2/T3 to motor)
      { index: 0, label: 'L1', x: 20, y: 0 },
      { index: 1, label: 'L2', x: 48, y: 0 },
      { index: 2, label: 'L3', x: 76, y: 0 },
      { index: 3, label: 'T1', x: 20, y: 72 },
      { index: 4, label: 'T2', x: 48, y: 72 },
      { index: 5, label: 'T3', x: 76, y: 72 },
      // Auxiliary NC contact (95-96) for coil interlock
      { index: 6, label: '95', x: 96, y: 22 },
      { index: 7, label: '96', x: 96, y: 50 },
    ],
  },
  dc_supply: {
    label: 'DC supply',
    description: 'DC power source (bench supply, wall-wart, buck converter)',
    width: 80,
    height: 64,
    color: '#0369a1',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: '+', x: 20, y: 64 },
      { index: 1, label: '-', x: 60, y: 64 },
    ],
  },
  battery: {
    label: 'Battery',
    description: 'DC battery bank (12 V / 24 V / 48 V)',
    width: 72,
    height: 64,
    color: '#166534',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: '+', x: 18, y: 0 },
      { index: 1, label: '-', x: 54, y: 0 },
    ],
  },
  kwh_meter: {
    label: 'kWh meter',
    description: 'Energy meter — pass-through with L/N in and L/N out',
    width: 96,
    height: 72,
    color: '#4b5563',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L in',  x: 24, y: 0 },
      { index: 1, label: 'N in',  x: 72, y: 0 },
      { index: 2, label: 'L out', x: 24, y: 72 },
      { index: 3, label: 'N out', x: 72, y: 72 },
    ],
  },
  mcb: {
    label: 'MCB',
    description: 'Miniature circuit breaker (1P)',
    width: 56,
    height: 64,
    color: '#1d4ed8',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L', x: 28, y: 0 },
      { index: 1, label: 'L', x: 28, y: 64 },
    ],
  },
  rcd: {
    label: 'RCD',
    description: 'Residual current device (2P, 30 mA)',
    width: 80,
    height: 72,
    color: '#059669',
    textColor: '#ffffff',
    ports: [
      { index: 0, label: 'L', x: 24, y: 0 },
      { index: 1, label: 'N', x: 56, y: 0 },
      { index: 2, label: 'L', x: 24, y: 72 },
      { index: 3, label: 'N', x: 56, y: 72 },
    ],
  },
  bell: {
    label: 'Bell / buzzer',
    description: 'Doorbell or buzzer — low-voltage load',
    width: 64,
    height: 64,
    color: '#eab308',
    textColor: '#111827',
    ports: [
      { index: 0, label: '+', x: 20, y: 0 },
      { index: 1, label: '-', x: 44, y: 0 },
    ],
  },
}

export const SCHEME_DEF_LIST = Object.entries(SCHEME_DEFS).map(([type, def]) => ({
  type: type as SchemeNodeType,
  ...def,
}))
